package com.moonteam.project.dao;

import com.moonteam.project.bean.VerifyCode;
import com.moonteam.project.bean.VerifyCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VerifyCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbggenerated Mon Oct 01 20:33:56 CST 2018
     */
    int countByExample(VerifyCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbggenerated Mon Oct 01 20:33:56 CST 2018
     */
    int deleteByExample(VerifyCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbggenerated Mon Oct 01 20:33:56 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbggenerated Mon Oct 01 20:33:56 CST 2018
     */
    int insert(VerifyCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbggenerated Mon Oct 01 20:33:56 CST 2018
     */
    int insertSelective(VerifyCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbggenerated Mon Oct 01 20:33:56 CST 2018
     */
    List<VerifyCode> selectByExample(VerifyCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbggenerated Mon Oct 01 20:33:56 CST 2018
     */
    VerifyCode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbggenerated Mon Oct 01 20:33:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") VerifyCode record, @Param("example") VerifyCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbggenerated Mon Oct 01 20:33:56 CST 2018
     */
    int updateByExample(@Param("record") VerifyCode record, @Param("example") VerifyCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbggenerated Mon Oct 01 20:33:56 CST 2018
     */
    int updateByPrimaryKeySelective(VerifyCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify_code
     *
     * @mbggenerated Mon Oct 01 20:33:56 CST 2018
     */
    int updateByPrimaryKey(VerifyCode record);
    /**
     *  电话号码对应的最新的验证码有没过期
     * @param cellphone
     * @return
     */
    VerifyCode selectLastestByCellPhone(@Param("cellphone")String cellphone);
}