package com.moonteam.project.bean;

import java.util.Date;

public class VerifyCode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_code.id
     *
     * @mbggenerated Mon Oct 01 20:33:56 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_code.cellphone
     *
     * @mbggenerated Mon Oct 01 20:33:56 CST 2018
     */
    private String cellphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_code.vcode
     *
     * @mbggenerated Mon Oct 01 20:33:56 CST 2018
     */
    private String vcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verify_code.create_time
     *
     * @mbggenerated Mon Oct 01 20:33:56 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_code.id
     *
     * @return the value of verify_code.id
     *
     * @mbggenerated Mon Oct 01 20:33:56 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_code.id
     *
     * @param id the value for verify_code.id
     *
     * @mbggenerated Mon Oct 01 20:33:56 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_code.cellphone
     *
     * @return the value of verify_code.cellphone
     *
     * @mbggenerated Mon Oct 01 20:33:56 CST 2018
     */
    public String getCellphone() {
        return cellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_code.cellphone
     *
     * @param cellphone the value for verify_code.cellphone
     *
     * @mbggenerated Mon Oct 01 20:33:56 CST 2018
     */
    public void setCellphone(String cellphone) {
        this.cellphone = cellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_code.vcode
     *
     * @return the value of verify_code.vcode
     *
     * @mbggenerated Mon Oct 01 20:33:56 CST 2018
     */
    public String getVcode() {
        return vcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_code.vcode
     *
     * @param vcode the value for verify_code.vcode
     *
     * @mbggenerated Mon Oct 01 20:33:56 CST 2018
     */
    public void setVcode(String vcode) {
        this.vcode = vcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verify_code.create_time
     *
     * @return the value of verify_code.create_time
     *
     * @mbggenerated Mon Oct 01 20:33:56 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verify_code.create_time
     *
     * @param createTime the value for verify_code.create_time
     *
     * @mbggenerated Mon Oct 01 20:33:56 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}